name: Notify Telegram
description: 'Send notification to a Telegram bot when a workflow fails'
inputs:
  bot_token:
    description: 'Telegram bot API token'
    required: true
  chat_id:
    description: 'Telegram chat ID to send the message to'
    required: true
runs:
  using: 'docker'
  image: 'docker://alpine/curl'
  env:
    BOT_TOKEN: ${{ inputs.bot_token }}
    CHAT_ID: ${{ inputs.chat_id }}
  args:
    - sh 
    - -c
    - |
      MESSAGE="Failed! Hello from pipeline!"
      curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text="${MESSAGE}"
  
  # from plain runner
  #using: composite
  #steps:
  #  - name: send-message
  #    shell: sh
  #    env:
  #      BOT_TOKEN: ${{ inputs.bot_token }}
  #      CHAT_ID: ${{ inputs.chat_id }}
  #    run: |
  #      MESSAGE="Failed! Hello from pipeline!"
  #      curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text="${MESSAGE}"
