name: Notify Telegram
description: 'Send notification to a Telegram bot when a workflow fails'
inputs:
  bot_token:
    description: 'Telegram bot API token'
    required: true
  chat_id:
    description: 'Telegram chat ID to send the message to'
    required: true
runs:
  using: 'docker'
  image: 'docker://alpine/curl'
  env:
    BOT_TOKEN: ${{ inputs.bot_token }}
    CHAT_ID: ${{ inputs.chat_id }}
  args:
    #- "MESSAGE=':warning: Workflow failed on ${{ github.repository }}: ${{ github.workflow }}.\n\nCheck it out here: ${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}'"
    #- MESSAGE="Failed! Hello from pipeline!"
    - curl -s -X POST "https://api.telegram.org/bot5650270379:AAGinGiLGbrXMqWu2NqZ-N-lXlstrFs-V2Y/sendMessage" -d chat_id=-837615955 -d text="Test from pipeline"
