name: Delivery
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      #TODO build image
      #TODO push to hub
      - name: Test telegram
        run: exit 1
      #- name: Notify Telegram on failure
      #  if: failure()
      #  uses: sanjin94/HFMpred/.ci/actions/telegram_warning.yaml
      #  with:
      #    telegram-bot-token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      #    telegram-chat-id: ${{ secrets.TELEGRAM_CHAT_ID }}
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      #- name: Lint code
      #  uses: sanjin94/HFMpred/.ci/actions/static_test.yaml
      #  with:
      #    pylint-options: ${{ inputs.pylint-options }}
      #TODO
      #- name: Test code
      #  run: pytest tests/
      - name: Test telegram
        run: exit 1
      #- name: Notify Telegram on failure
      #  if: failure()
      #  uses: sanjin94/HFMpred/.ci/actions/telegram_warning.yaml
      #  with:
      #    telegram-bot-token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      #    telegram-chat-id: ${{ secrets.TELEGRAM_CHAT_ID }}

