name: Pylint
description: 'Run Pylint on Python code'
inputs:
  pylint-options:
    description: 'Additional command-line options to pass to Pylint'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'python:3.10-slim-buster'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Run Pylint
      shell: bash
      run: |
        pylint $(git ls-files '*.py') ${{ inputs.pylint-options }}
        # find . -type f -name "*.py" | xargs pylint
